config/routes.rb
Rails.application.routes.draw do
  root to: "homes#show"
  get "auth/github", as: :github_login
  get "auth/github/callback", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: :logout
  resources :users, only: [:show] do
    resources :activities, only: [:index]
    resources :repositories, only: [:index]
    resources :organizations, only: [:index]
  end
end

app/models/activity.rb
class Activity < OpenStruct
  attr_reader :repo_name, :message, :created_at, :nickname
  def initialize(event)
    @repo_name = event["repo"]["name"]
    @message = event["payload"]["commits"].first["message"]
    @created_at = DateTime.parse(event["created_at"]).strftime("%A, %B %e, %Y")
    @nickname = event["actor"]["login"]
  end

  def self.recent_activity(current_user)
    response = UserServices.new(current_user).recent_activity
    push_events = response.select { |event| event["type"] == "PushEvent" }
    push_events.map do |event|
      Activity.new(event)
    end
  end

  def self.received_activity(current_user)
    response = UserServices.new(current_user).received_activity
    push_events = response.select { |event| event["type"] == "PushEvent" }
    push_events.map do |event|
      Activity.new(event)
    end
  end
end

app/models/organization.rb
class Organization < OpenStruct
  attr_reader :name
  def initialize(org)
    @name = org["name"]
  end

  def self.all(current_user)
    response = UserServices.new(current_user).organizations
    response.map do |org|
      Organization.new(org)
    end
  end
end

app/models/repository.rb
class Repository < OpenStruct
  attr_reader :name
  def initialize(repo)
    @name = repo["full_name"]
  end

  def self.starred_repositories(current_user)
    response = UserServices.new(current_user).starred_repositories
    response.map do |repo|
      Repository.new(repo)
    end
  end

  def self.all_repositories(current_user)
    response = UserServices.new(current_user).all_repositories
    response.map do |repo|
      Repository.new(repo)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.name               = auth_info.info.name
      new_user.nickname           = auth_info.info.nickname
      new_user.oauth_token        = auth_info.credentials.token
      new_user.avatar_url         = auth_info.extra.raw_info.avatar_url
    end
  end

  def followers
    UserServices.new(self).followers
  end

  def following
    UserServices.new(self).following
  end

  def starred_repositories
    UserServices.new(self).starred_repositories
  end

  def all_repositories
    UserServices.new(self).all_repositories
  end

  def organizations
    UserServices.new(self).organizations
  end

  def recent_activity
    UserServices.new(self).recent_activity
  end

  def received_activity
    UserServices.new(self).received_activity
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = Activity.recent_activity(current_user)
    @received_activities = Activity.received_activity(current_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
    @organizations = Organization.all(current_user)
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  def index
    @starred_repositories = Repository.starred_repositories(current_user)
    @all_repositories = Repository.all_repositories(current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to user_path(user.id)
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/index.html.erb
<h3>Recent activity for <%= current_user.name %> </h3>
<% @activities.map do |activity| %>
<ul>
  <li>
  <strong>Repository Name:</strong> <%= activity.repo_name %>
  <br><strong>Commit Message:</strong> <%= activity.message %>
  <br><strong>Created Date:</strong> <%= activity.created_at %>
</li>
</ul>
<% end %>
<h3>Received activity for <%= current_user.name %> </h3>
<% @received_activities.map do |activity| %>
<ul>
  <li>
  <strong>Repository Name:</strong> <%= activity.repo_name %>
  <br><strong>Commit Message:</strong> <%= activity.message %>
  <br><strong>Created Date:</strong> <%= activity.created_at %>
  <br><% if activity.nickname != current_user.nickname %>
  <strong>User:</strong> <%= activity.nickname %>
  <% end %>
</li>
</ul>
<% end %>

app/views/homes/show.html.erb
<h1>Hello!!!!</h1>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button class="navbar-toggle" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Git Lucky</a>
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li>
        <% if current_user %>
          Hello, <%= current_user.name.split(" ").first %>
          <%= link_to "Logout", logout_path, method: :delete %>
          <% else %>
          <%= link_to "Log in with Github", github_login_path %>
          <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Git Lucky</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= render 'layouts/navbar' %>
  <%= yield %>

</body>
</html>

app/views/organizations/index.html.erb
<h1>Organizations for <%= current_user.name %> (<%=@organizations.count%>)</h1>
<% @organizations.map do |org| %>
<ul>
  <li>
  <strong>Organization Name:</strong> <%= org.name %>
  </li>
</ul>
<% end %>

app/views/repositories/index.html.erb
<h1>Repositories for <%= current_user.name %></h1>
<h3>Starred Repositories (<%= @starred_repositories.count %>)</h3>
<% @starred_repositories.map do |repo| %>
<ul>
  <li>
  <strong>Repository Name:</strong> <%= repo.name %>
  </li>
</ul>
<% end %>

<h3>All Repositories (<%= @all_repositories.count%>) </h3>
<% @all_repositories.map do |repo| %>
<ul>
  <li>
  <strong>Repository Name:</strong> <%= repo.name %>
  </li>
</ul>
<% end %>

app/views/users/show.html.erb
<%= image_tag(@user.avatar_url) %>
<h1><%= @user.name %></h1>
<br>
<h3>All repositories: </h3>
<%= link_to "View all repositories", user_repositories_path(@user) %>

<br>
<h3>Starred repositories:</h3>
<%= link_to "View starred repositories", user_repositories_path(@user) %>
<br>

<h3>Your followers (<%= @user.followers.count %>):</h3>
<% @user.followers.each do |follower| %>
  <ul>
    <li> <%= follower["login"] %> </li>
  </ul>
  <% end %>
<br>

<h3>Recent activity</h3>
<%= link_to "View user activity", user_activities_path(@user) %>


<h3>You're following (<%= @user.following.count %>):</h3>
<% @user.following.each do |following| %>
  <ul>
    <li> <%= following["login"] %> </li>
  </ul>
  <% end %>
<br>
<h3>Organizations</h3>
<%= link_to "View all organizations", user_organizations_path(@user) %>